//go:generate stringer -type=Code

package kbd

// Key Code
// https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx
const (
	Cancel            Code = 0x03 // Control-break processing
	Backspace         Code = 0x08 // BACKSPACE key
	Tab               Code = 0x09 // TAB key
	Clear             Code = 0x0C // CLEAR key
	Return            Code = 0x0D // ENTER key
	Shift             Code = 0x10 // SHIFT key
	Control           Code = 0x11 // CTRL key
	Alt               Code = 0x12 // ALT key
	Pause             Code = 0x13 // PAUSE key
	CapsLock          Code = 0x14 // CAPS LOCK key
	Escape            Code = 0x1B // ESC key
	Space             Code = 0x20 // SPACEBAR
	PageUp            Code = 0x21 // PAGE UP key
	PageDown          Code = 0x22 // PAGE DOWN key
	End               Code = 0x23 // END key
	Home              Code = 0x24 // HOME key
	Left              Code = 0x25 // LEFT ARROW key
	Up                Code = 0x26 // UP ARROW key
	Right             Code = 0x27 // RIGHT ARROW key
	Down              Code = 0x28 // DOWN ARROW key
	Select            Code = 0x29 // SELECT key
	Print             Code = 0x2A // PRINT key
	Execute           Code = 0x2B // EXECUTE key
	PrintScreen       Code = 0x2C // PRINT SCREEN key
	Insert            Code = 0x2D // INS key
	Delete            Code = 0x2E // DEL key
	Help              Code = 0x2F // HELP key
	Key0              Code = 0x30 // 0 key
	Key1              Code = 0x31 // 1 key
	Key2              Code = 0x32 // 2 key
	Key3              Code = 0x33 // 3 key
	Key4              Code = 0x34 // 4 key
	Key5              Code = 0x35 // 5 key
	Key6              Code = 0x36 // 6 key
	Key7              Code = 0x37 // 7 key
	Key8              Code = 0x38 // 8 key
	Key9              Code = 0x39 // 9 key
	KeyA              Code = 0x41 // A key
	KeyB              Code = 0x42 // B key
	KeyC              Code = 0x43 // C key
	KeyD              Code = 0x44 // D key
	KeyE              Code = 0x45 // E key
	KeyF              Code = 0x46 // F key
	KeyG              Code = 0x47 // G key
	KeyH              Code = 0x48 // H key
	KeyI              Code = 0x49 // I key
	KeyJ              Code = 0x4A // J key
	KeyK              Code = 0x4B // K key
	KeyL              Code = 0x4C // L key
	KeyM              Code = 0x4D // M key
	KeyN              Code = 0x4E // N key
	KeyO              Code = 0x4F // O key
	KeyP              Code = 0x50 // P key
	KeyQ              Code = 0x51 // Q key
	KeyR              Code = 0x52 // R key
	KeyS              Code = 0x53 // S key
	KeyT              Code = 0x54 // T key
	KeyU              Code = 0x55 // U key
	KeyV              Code = 0x56 // V key
	KeyW              Code = 0x57 // W key
	KeyX              Code = 0x58 // X key
	KeyY              Code = 0x59 // Y key
	KeyZ              Code = 0x5A // Z key
	LeftWin           Code = 0x5B // Left Windows key
	RightWin          Code = 0x5C // Right Windows key
	Apps              Code = 0x5D // Applications key (right click)
	Sleep             Code = 0x5F // Computer Sleep key
	Numpad0           Code = 0x60 // Numeric keypad 0 key
	Numpad1           Code = 0x61 // Numeric keypad 1 key
	Numpad2           Code = 0x62 // Numeric keypad 2 key
	Numpad3           Code = 0x63 // Numeric keypad 3 key
	Numpad4           Code = 0x64 // Numeric keypad 4 key
	Numpad5           Code = 0x65 // Numeric keypad 5 key
	Numpad6           Code = 0x66 // Numeric keypad 6 key
	Numpad7           Code = 0x67 // Numeric keypad 7 key
	Numpad8           Code = 0x68 // Numeric keypad 8 key
	Numpad9           Code = 0x69 // Numeric keypad 9 key
	NumpadMultiply    Code = 0x6A // Multiply key
	NumpadAdd         Code = 0x6B // Add key
	Separator         Code = 0x6C // Separator key
	NumpadSubtract    Code = 0x6D // Subtract key
	NumpadDecimal     Code = 0x6E // Decimal key
	NumpadDivide      Code = 0x6F // Divide key
	F1                Code = 0x70 // F1 key
	F2                Code = 0x71 // F2 key
	F3                Code = 0x72 // F3 key
	F4                Code = 0x73 // F4 key
	F5                Code = 0x74 // F5 key
	F6                Code = 0x75 // F6 key
	F7                Code = 0x76 // F7 key
	F8                Code = 0x77 // F8 key
	F9                Code = 0x78 // F9 key
	F10               Code = 0x79 // F10 key
	F11               Code = 0x7A // F11 key
	F12               Code = 0x7B // F12 key
	F13               Code = 0x7C // F13 key
	F14               Code = 0x7D // F14 key
	F15               Code = 0x7E // F15 key
	F16               Code = 0x7F // F16 key
	F17               Code = 0x80 // F17 key
	F18               Code = 0x81 // F18 key
	F19               Code = 0x82 // F19 key
	F20               Code = 0x83 // F20 key
	F21               Code = 0x84 // F21 key
	F22               Code = 0x85 // F22 key
	F23               Code = 0x86 // F23 key
	F24               Code = 0x87 // F24 key
	NumLock           Code = 0x90 // NUM LOCK key
	Scroll            Code = 0x91 // SCROLL LOCK key
	LeftShift         Code = 0xA0 // Left SHIFT key
	RightShift        Code = 0xA1 // Right SHIFT key
	LeftControl       Code = 0xA2 // Left CONTROL key
	RightControl      Code = 0xA3 // Right CONTROL key
	LeftAlt           Code = 0xA4 // Left MENU key
	RightAlt          Code = 0xA5 // Right MENU key
	BrowserBack       Code = 0xA6 // Browser Back key
	BrowserForward    Code = 0xA7 // Browser Forward key
	BrowserRefresh    Code = 0xA8 // Browser Refresh key
	BrowserStop       Code = 0xA9 // Browser Stop key
	BrowserSearch     Code = 0xAA // Browser Search key
	BrowserFavorites  Code = 0xAB // Browser Favorites key
	BrowserHome       Code = 0xAC // Browser Start and Home key
	VolumeMute        Code = 0xAD // Volume Mute key
	VolumeDown        Code = 0xAE // Volume Down key
	VolumeUp          Code = 0xAF // Volume Up key
	MediaNextTrack    Code = 0xB0 // Next Track key
	MediaPrevTrack    Code = 0xB1 // Previous Track key
	MediaStop         Code = 0xB2 // Stop Media key
	MediaPlayPause    Code = 0xB3 // Play/Pause Media key
	LaunchMail        Code = 0xB4 // Start Mail key
	LaunchMediaSelect Code = 0xB5 // Select Media key
	LaunchApp1        Code = 0xB6 // Start Application 1 key
	LaunchApp2        Code = 0xB7 // Start Application 2 key
	Colon             Code = 0xBA // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ';:' key
	Plus              Code = 0xBB // For any country/region, the '+' key
	Comma             Code = 0xBC // For any country/region, the ',' key
	Minus             Code = 0xBD // For any country/region, the '-' key
	Period            Code = 0xBE // For any country/region, the '.' key
	Slash             Code = 0xBF // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '/?' key
	Tilde             Code = 0xC0 // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '`~' key
	OpenBracket       Code = 0xDB // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '[{' key
	Backslash         Code = 0xDC // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '\|' key
	CloseBracket      Code = 0xDD // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ']}' key
	Quote             Code = 0xDE // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the 'single-quote/double-quote' key
	Packet            Code = 0xE7 // Used to pass Unicode characters as if they were keystrokes. The PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP
	Attn              Code = 0xF6 // Attn key
	CrSel             Code = 0xF7 // CrSel key
	ExSel             Code = 0xF8 // ExSel key
	EraseEOF          Code = 0xF9 // Erase EOF key
	Play              Code = 0xFA // Play key
	Zoom              Code = 0xFB // Zoom key
	Pa1               Code = 0xFD // PA1 key
	OemClear          Code = 0xFE // Clear key
)
